name: Build production files and bump version

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # At the time being, seems like caching isn't required. Direct install seems faster than cache load
      # @link https://github.com/oven-sh/setup-bun/issues/14#issuecomment-1714116221

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch # Can be set to major, minor, or patch
          GIT_API_TAGGING: false # Fix for tag push reference error
          WITH_V: false # If you want your tag to start with 'v', e.g., v1.0.0
